/* NOME DOS INTEGRANTES DO GRUPO: 
DANIEL HENRIQUUE LOPES HONORATO RA: 03261035
LENNY STEPHANO RA:03261004
EMILLY LUIZA RA: 03261006
JULIA SILVA DE LEMOS RA: 03261054
ANDREY BRASLAUSKAS RA: 03261060
THOR LANDIM SECCO RA: 03261058
MARIA PAULA RA: 03261052
*/
-- CRIAÇÃO DO BANCO DE DADOS
CREATE DATABASE MONITORAMENTO_SERVIDORES;
USE MONITORAMENTO_SERVIDORES;

-- TABELA PARA OS ADMINISTRADORES/DONOS DO SISTEMA
CREATE TABLE ADMINISTRADOR (
    ID_ADMIN INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    SENHA_ADM VARCHAR(50) NOT NULL,
    CARGO VARCHAR(100) DEFAULT 'ADMINISTRADOR DA EMPRESA',
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- TABELA PARA A EMPRESA
CREATE TABLE EMPRESA (
    ID_EMPRESA INT AUTO_INCREMENT PRIMARY KEY,
    CNPJ CHAR(18) NOT NULL UNIQUE,
    SENHA_EMPRESA VARCHAR (255) NOT NULL,
    NOME_EMPRESA VARCHAR(150) NOT NULL,
    CONTATO_RESPONSAVEL VARCHAR(100) NOT NULL,
    EMAIL_ALERTA VARCHAR(150) NOT NULL,
    ENDERECO_EMPRESA VARCHAR(255) NOT NULL
);

CREATE TABLE FUNCIONARIOS (
	ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
	ID_EMPRESA INT NOT NULL,
	SENHA_FUNCIONARIO VARCHAR(50) NOT NULL,
	NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
	EMAIL_FUNCIONARIO VARCHAR(100) NOT NULL,
	TELEFONE_FUNCIONARIO VARCHAR(17),
	CARGO_FUNCIONARIO VARCHAR(100) -- EMPRESA QUE IRA DESIGNAR O CARGO DO FUNCIONARIO
);

-- TABELA PARA CADASTRAR OS SENSORES NO AMBIENTE DOS SERVIDORES
CREATE TABLE SENSOR (
    ID_SENSOR INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    IDENTIFICACAO_LOCAL VARCHAR(100) NOT NULL, -- EX: 'RACK PRINCIPAL', 'ENTRADA DE AR'
    STATUS_SENSOR VARCHAR(20) DEFAULT 'Pendente',
    CHECK(STATUS_SENSOR IN ('Ativo', 'Inativo', 'Pendente', 'Em manutenção'))
);

-- TABELA PARA REGISTRAR O HISTÓRICO DE LEITURAS DE TEMPERATURA E UMIDADE
CREATE TABLE HISTORICO (
    ID_LEITURA INT AUTO_INCREMENT PRIMARY KEY,
    ID_SENSOR INT NOT NULL,
    TEMPERATURA DECIMAL(5,2) NOT NULL,
    UMIDADE DECIMAL(5,2) NOT NULL,
    DATA_HORA_MEDICAO DATETIME DEFAULT CURRENT_TIMESTAMP
);


-- INSERTS 
INSERT INTO ADMINISTRADOR (NOME, EMAIL, SENHA_ADM, CARGO)
VALUES 
('ANDREY MAIO SARAMENTO BRAUSLAUSKAS', 'ANDREY@SISTEMA.COM.BR', 'SENHA', 'DESENVOLVEDOR BACK-END'),
('DANIEL HENRIQUE LOPES HONORATO', 'DANIEL@SISTEMA.COM.BR', 'SENHA', 'DBA / GESTOR DE DADOS'),
('EMILLY LUIZA MAFFEI DE OLIVEIRA', 'EMILLY@SISTEMA.COM.BR', 'SENHA', 'ANALISTA DE INFRAESTRUTURA'),
('JÚLIA SILVA DE LEMOS', 'JULIA@SISTEMA.COM.BR', 'SENHA', 'DESENVOLVEDORA FRONT-END'),
('LENNY STEPHANO', 'LENNY@SISTEMA.COM.BR', 'SENHA', 'ESPECIALISTA EM IOT'),
('MARIA PAULA MARQUES BONFIM', 'MARIA@SISTEMA.COM.BR', 'SENHA', 'GERENTE DE PROJETOS'),
('THOR LANDIM SECCO', 'THOR@SISTEMA.COM.BR', 'SENHA', 'ANALISTA DE SEGURANÇA');



INSERT INTO EMPRESA (CNPJ, SENHA_EMPRESA, NOME_EMPRESA, CONTATO_RESPONSAVEL, EMAIL_ALERTA, ENDERECO_EMPRESA)
VALUES ('12.345.678/0001-90', 'SENHA123', 'TECH CORP SOLUTIONS', 'JOÃO SILVA', 'ALERTA@TECHCORP.COM.BR', 'AV. PAULISTA, 1000 - SÃO PAULO');


INSERT INTO FUNCIONARIOS (ID_EMPRESA, SENHA_FUNCIONARIO, NOME_FUNCIONARIO, EMAIL_FUNCIONARIO, TELEFONE_FUNCIONARIO, CARGO_FUNCIONARIO)
VALUES (1, 'SENHA456', 'CARLOS ALMEIDA', 'CARLOS@TECHCORP.COM.BR', '(11) 98765-4321', 'GERENTE DE TI');


INSERT INTO SENSOR (ID_EMPRESA, IDENTIFICACAO_LOCAL, STATUS_SENSOR)
VALUES (1, 'SALA DE SERVIDORES - RACK 01', 'Ativo');


INSERT INTO HISTORICO (ID_SENSOR, TEMPERATURA, UMIDADE)
VALUES 
(1, 23.50, 45.00), -- Leitura normal
(1, 28.10, 56.00); -- Simulando uma leitura de alerta (temperatura alta)



-- SELECTS
SELECT * FROM ADMINISTRADOR;

SELECT * FROM EMPRESA;

SELECT * FROM FUNCIONARIOS;

SELECT * FROM SENSOR;

SELECT * FROM HISTORICO;

SELECT 
    ID_LEITURA,
    ID_SENSOR,
    TEMPERATURA,
    UMIDADE,
    DATA_HORA_MEDICAO,
    CASE 
        WHEN TEMPERATURA < 18.00 THEN 'ATENÇÃO: MUITO FRIO (Risco de condensação)'
        WHEN TEMPERATURA >= 18.00 AND TEMPERATURA <= 27.00 THEN 'IDEAL: OPERAÇÃO SEGURA'
        WHEN TEMPERATURA > 27.00 AND TEMPERATURA <= 35.00 THEN 'ALERTA AMARELO: AQUECIMENTO ANORMAL'
        WHEN TEMPERATURA > 35.00 THEN 'ALERTA VERMELHO: RISCO CRÍTICO DE PARADA'
    END AS STATUS_TEMPERATURA
FROM HISTORICO;
